# src/pipelines/message_logger/config-template.toml

# 消息日志管道配置模板
# 首次运行时，系统将自动复制此文件生成 config.toml
# 请在 config.toml 中修改配置，而不是直接修改此模板

[message_logger]
# 是否启用此管道 (注意：此项在主配置中也需要设置优先级)
enabled = true

# 日志文件存储目录
logs_dir = "logs/messages"

# 日志文件名前缀
file_prefix = "messages_"

# 日志文件扩展名
file_extension = ".jsonl"

# 当没有群组ID时使用的默认ID
default_group_id = "default"

# 是否包含原始消息内容
include_raw_message = true

# 日志文件轮转间隔（秒），默认86400（一天）
rotation_interval = 86400

# 缓冲区刷新间隔（秒），默认10秒
flush_interval = 10
